### PR TITLE
Add Support for Laravel 10.x

### PR DESCRIPTION
**Pull request by hebbet**
tested it in some of my process and didn't run in any issues

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Thank you for PR.

Can you add version `^8.0` of the `orchestra/testbench` project to test the project locally and also update the [`.github/workflows/phpunit.yml`](https://github.com/Laravel-Lang/publisher/blob/main/.github/workflows/phpunit.yml) file?

Laravel 10 is [scheduled to release](https://laravel.com/docs/9.x/releases#support-policy) on February 7th, so we can test this release PR on Tuesday.

**Comment by hebbet** [comment]
done.

image

**Comment by andrey-helldar** [comment]
Thank you! Now we are waiting for February 7th :)

**Comment by andrey-helldar** [comment]
Thank you

**Pull request merged**
